#include "chip8.h"

/* Opcodes */
void _0nnn(chip8_hw*, unsigned);
void _00E0(chip8_hw*, unsigned);
void _00EE(chip8_hw*, unsigned);
void _1NNN(chip8_hw*, unsigned);
void _2NNN(chip8_hw*, unsigned);
void _3XNN(chip8_hw*, unsigned);
void _4XNN(chip8_hw*, unsigned);
void _5XY0(chip8_hw*, unsigned);
void _6XNN(chip8_hw*, unsigned);
void _7XNN(chip8_hw*, unsigned);
void _8XY0(chip8_hw*, unsigned);
void _8XY1(chip8_hw*, unsigned);
void _8XY2(chip8_hw*, unsigned);
void _8XY3(chip8_hw*, unsigned);
void _8XY4(chip8_hw*, unsigned);
void _8XY5(chip8_hw*, unsigned);
void _8XY6(chip8_hw*, unsigned);
void _8XY7(chip8_hw*, unsigned);
void _8XYE(chip8_hw*, unsigned);
void _9XY0(chip8_hw*, unsigned);
void _ANNN(chip8_hw*, unsigned);
void _BNNN(chip8_hw*, unsigned);
void _CXNN(chip8_hw*, unsigned);
void _DXYN(chip8_hw*, unsigned);
void _EX9E(chip8_hw*, unsigned);
void _EXA1(chip8_hw*, unsigned);
void _FX07(chip8_hw*, unsigned);
void _FX0A(chip8_hw*, unsigned);
void _FX15(chip8_hw*, unsigned);
void _FX18(chip8_hw*, unsigned);
void _FX1E(chip8_hw*, unsigned);
void _FX29(chip8_hw*, unsigned);
void _FX33(chip8_hw*, unsigned);
void _FX55(chip8_hw*, unsigned);
void _FX65(chip8_hw*, unsigned);

